#!/usr/bin/env bash
################################################################################
#  Environment variables and inclusions.
################################################################################

# Make vim the default editor
export EDITOR="vim"

HISTSIZE=32768  # Larger bash history (allow 32³ entries; default is 500)
HISTFILESIZE=$HISTSIZE
HISTCONTROL=ignoredups
HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"  # no store dull/risky commands.
HISTFILE=$HOME/.history  # unify bash and zsh history

# Prefer US English and use UTF-8
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

# Highlight section titles in manual pages
LESS_TERMCAP_md="$ORANGE"

# Don’t clear the screen after quitting a manual page
MANPAGER="less -FXRS"
PAGER="less -FXRS"

# Always enable colored `grep` output
GREP_OPTIONS="--color=auto"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
HOMEBREW_CASK_OPTS="--appdir=/Applications"

