#!/usr/bin/env bash
################################################################################
#  Environment variables and inclusions.
################################################################################

# Make vim the default editor
export EDITOR="vim"

export TERM=xterm-256color

export HISTSIZE=32768  # Larger bash history (allow 32³ entries; default is 500)
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTIGNORE="ls:cd:cd -:pwd:exit:date:* --help"  # no store dull/risky commands.
export HISTFILE=$HOME/.history  # unify bash and zsh history

# Prefer Irish English and use UTF-8
export LANG="en_IE.UTF-8"
export LC_ALL="en_IE.UTF-8"

# Highlight section titles in manual pages
export LESS_TERMCAP_md="$ORANGE"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -FXRS"
export PAGER="less -FXRS"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# fuzzy finder shortcut installation
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
